# Generated by Django 5.2 on 2025-04-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicationdose",
            name="status",
            field=models.CharField(
                choices=[
                    ("On Time", "On Time"),
                    ("Missed", "Missed"),
                    ("Taken", "Taken"),
                ],
                max_length=20,
            ),
        ),
    ]
