# Generated by Django 5.2 on 2025-04-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0002_alter_medicationdose_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicationdose",
            name="actual_time_taken",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
