# Generated by Django 5.2 on 2025-05-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0003_medicationdose_actual_time_taken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicationdose",
            name="status",
            field=models.CharField(
                choices=[
                    ("On Time", "On Time"),
                    ("Missed", "Missed"),
                    ("Taken", "Taken"),
                    ("Taken On Time", "Taken On Time"),
                    ("Taken Late", "Taken Late"),
                    ("Scheduled", "Scheduled"),
                ],
                default="Scheduled",
                max_length=20,
            ),
        ),
    ]
