# Generated by Django 5.2 on 2025-05-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carer",
            fields=[
                (
                    "CarerID",
                    models.AutoField(
                        db_column="CarerID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "type_of_carer",
                    models.CharField(
                        blank=True, db_column="TypeofCarer", max_length=50, null=True
                    ),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        blank=True,
                        db_column="PreferredContactMethod",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, db_column="PhoneNumber", max_length=20, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="Email", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "Carers",
                "managed": False,
            },
        ),
    ]
