# Generated by Django 5.2 on 2025-05-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "patient_id",
                    models.CharField(
                        db_column="PatientID",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=100)),
                ("date_of_birth", models.DateField(db_column="DateOfBirth")),
                (
                    "gender",
                    models.CharField(
                        choices=[("Female", "Female"), ("Male", "Male")],
                        db_column="Gender",
                        max_length=10,
                    ),
                ),
                ("age", models.IntegerField(db_column="Age")),
            ],
            options={
                "db_table": "Patients",
                "managed": False,
            },
        ),
    ]
