# Generated by Django 5.2 on 2025-04-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicationType",
            fields=[
                (
                    "med_type_id",
                    models.AutoField(
                        db_column="MedTypeID", primary_key=True, serialize=False
                    ),
                ),
                ("med_name", models.CharField(db_column="MedName", max_length=100)),
            ],
            options={
                "db_table": "MedicationTypes",
                "managed": False,
            },
        ),
    ]
