# Generated by Django 5.2 on 2025-04-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userid",
                    models.AutoField(
                        db_column="UserID", primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(db_column="Username", max_length=100)),
                ("password", models.CharField(db_column="Password", max_length=255)),
                ("role", models.CharField(db_column="Role", max_length=10)),
                (
                    "patient_id",
                    models.CharField(db_column="PatientID", max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "Users",
                "managed": False,
            },
        ),
    ]
